name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  call-ci-workflow:
    uses: marksdemoorg/workflow-templates/.github/workflows/dot-net-build-test.yml@main
  call-ci-codeul-workflow:
    uses: marksdemoorg/workflow-templates/.github/workflows/ci-codeql.yml@main
