name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  call-ci-workflow:
    uses: marksdemoorg/workflow-templates/blob/main/marks-demo-org-ci.yml@main
